// Sprite file manifest - auto-generated list of sprite files
const spriteFiles = [
    'arrow.js',
    'baby_endermite.js',
    'baby_ghast.js',
    'baby_warden.js',
    'bat.js',
    'blaze.js',
    'blazeRod.js',
    'blue_ender_pearl.js',
    'breeze.js',
    'bubble.js',
    'chicken.js',
    'corruptedBeacon.js',
    'creeper.js',
    'creepernado.js',
    'crossbowBolt.js',
    'devourer.js',
    'diamondSword.js',
    'drowned.js',
    'egg.js',
    'elder_guardian.js',
    'end_golem.js',
    'end_monstrosity.js',
    'enderPearl.js',
    'ender_dragon.js',
    'enderman.js',
    'endermanHead.js',
    'enderman_head.js',
    'endermite.js',
    'endersent.js',
    'endwither.js',
    'evoker.js',
    'firePotion.js',
    'fireSpread.js',
    'fireball.js',
    'ghast.js',
    'goldenApple.js',
    'great_hog.js',
    'guardian.js',
    'harpArrow.js',
    'harpCrossbow.js',
    'heart_of_ender.js',
    'heartstealerEgg.js',
    'hungryHorror.js',
    'iron_golem.js',
    'lightningBolt.js',
    'nightmareBat.js',
    'nightmaresBite.js',
    'piglin.js',
    'piglin_legends.js',
    'pinkLaser.js',
    'pink_beam.js',
    'pink_square.js',
    'polar_bear.js',
    'ravager.js',
    'redstone.js',
    'ricochetEgg.js',
    'shield.js',
    'shulker.js',
    'skeleton.js',
    'slime.js',
    'small_endermite.js',
    'snow_fox.js',
    'snowball.js',
    'stevesLavaChicken.js',
    'stormlander.js',
    'sunsGrace.js',
    'sunsGraceFireball.js',
    'swiftness.js',
    'the_endermite.js',
    'tinyHorror.js',
    'tnt.js',
    'tornado.js',
    'totem.js',
    'tractorBeam.js',
    'vengeful_heart_of_ender.js',
    'vex.js',
    'vindicator.js',
    'violet.js',
    'voidVoyager.js',
    'warden.js',
    'wargen.js',
    'windCharge.js',
    'witch.js',
    'wither.js',
    'wither_skeleton.js',
    'wolf.js',
    'zombie.js',
    'zombie_piglin.js',
];

// Load all sprite files dynamically
function loadSprites() {
    const scripts = spriteFiles.map(file => {
        return new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = 'js/sprites/' + file;
            script.onload = resolve;
            script.onerror = reject;
            document.head.appendChild(script);
        });
    });
    
    return Promise.all(scripts);
}
